"""initial migration

Revision ID: 4aea5b6cc9a1
Revises: 
Create Date: 2018-05-22 12:49:56.304581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4aea5b6cc9a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=55), nullable=False),
    sa.Column('password', sa.VARCHAR(length=125), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('db_backup_status')
    op.drop_index('host', table_name='db_backup_host')
    op.drop_table('db_backup_host')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_backup_host',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('host', mysql.VARCHAR(collation=u'utf8_bin', length=50), nullable=True),
    sa.Column('port', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cn_name', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=True),
    sa.Column('remark', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_index('host', 'db_backup_host', ['host'], unique=True)
    op.create_table('db_backup_status',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('host', mysql.VARCHAR(collation=u'utf8_bin', length=40), nullable=True),
    sa.Column('code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=True),
    sa.Column('total_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mydump_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sync_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
